apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=   # base64 of 'username'
    mongo-root-password: cGFzc3dvcmQ=   # base64 of 'password'
